# Generated by Django 4.1.3 on 2023-01-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
